### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by sudo-Mystic** [JoseHenriqueSiqueira/Whatsapp_Instagram_Messanger_ChatGPT_OpenAI#4]
```Traceback (most recent call last):
  File "/home/username/Code/Whatsapp_Instagram_Messanger_ChatGPT_OpenAI/InstagramBot.py", line 8, in <module>
    from subprocess import CREATE_NO_WINDOW
ImportError: cannot import name 'CREATE_NO_WINDOW' from 'subprocess'
```
i am using Python3.9.16 , Zorin OS 16 (Ubuntu based)

Edit : i found this in documentation https://docs.python.org/3/library/subprocess.html#subprocess.CREATE_NO_WINDOW  does that mean it will only work in windows ???

**Comment by JoseHenriqueSiqueira** [comment]
the "CREATE NO WINDOW" constant is only available for Windows systems. You can remove the lines or comment them out.
```ruby
"from subprocess import CREATE_NO_WINDOW" line 8
"self.service.creationflags = CREATE_NO_WINDOW" line 16. 
```
Their purpose was just to prevent selinium from creating a terminal
